import type { Metadata } from "next";
import "./globals.css";
import {Menu} from "@/src/components/menu/Menu";

export const metadata: Metadata = {
  title: "Next App Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
      <Menu/>
      <div className="max-width-300 mx-auto">
        {children}
      </div>
      </body>
    </html>
  );
}
